// Code Generated by Sidekick is for learning and experimentation purposes only.
import mongoose, { type InferSchemaType } from "mongoose";

const AttachmentSchema = new mongoose.Schema(
  {
    ticketId: { type: mongoose.Schema.Types.ObjectId, ref: "Ticket", required: true, index: true },
    commentId: { type: mongoose.Schema.Types.ObjectId, ref: "Comment", default: null, index: true },
    uploadedBy: { type: mongoose.Schema.Types.ObjectId, ref: "User", required: true },

    originalFilename: { type: String, required: true, maxlength: 255 },
    mimeType: { type: String, required: true, maxlength: 80 },
    sizeBytes: { type: Number, required: true, min: 1, max: 10 * 1024 * 1024 },

    storageKey: { type: String, required: true, maxlength: 300 },
    data: { type: Buffer, required: true } // Binary data storage
  },
  { timestamps: { createdAt: true, updatedAt: false } }
);

AttachmentSchema.index({ ticketId: 1, createdAt: -1 });

export type IAttachment = InferSchemaType<typeof AttachmentSchema>;
export default mongoose.model<IAttachment>("Attachment", AttachmentSchema);
