// Code Generated by Sidekick is for learning and experimentation purposes only.
import mongoose, { type InferSchemaType } from "mongoose";
import { AUDIT_EVENT_TYPE, AUDIT_VISIBILITY } from "../utils/constants";

const AuditEventSchema = new mongoose.Schema(
  {
    ticketId: { type: mongoose.Schema.Types.ObjectId, ref: "Ticket", required: true, index: true },
    actorId: { type: mongoose.Schema.Types.ObjectId, ref: "User", required: true },

    eventType: { type: String, enum: Object.values(AUDIT_EVENT_TYPE), required: true },
    visibility: { type: String, enum: Object.values(AUDIT_VISIBILITY), default: AUDIT_VISIBILITY.PUBLIC, required: true },

    from: { type: mongoose.Schema.Types.Mixed },
    to: { type: mongoose.Schema.Types.Mixed },
    metadata: { type: mongoose.Schema.Types.Mixed },

    occurredAt: { type: Date, default: Date.now, index: true }
  },
  { versionKey: false }
);

AuditEventSchema.index({ ticketId: 1, occurredAt: 1 });

export type IAuditEvent = InferSchemaType<typeof AuditEventSchema>;
export default mongoose.model<IAuditEvent>("AuditEvent", AuditEventSchema);
