// Code Generated by Sidekick is for learning and experimentation purposes only.
import mongoose, { type InferSchemaType } from "mongoose";

const CategorySchema = new mongoose.Schema(
  {
    name: { type: String, trim: true, required: true, unique: true, maxlength: 80 },
    isActive: { type: Boolean, default: true },
    // sortOrder: { type: Number, default: 0 }
  },
  { timestamps: true }
);

export type ICategory = InferSchemaType<typeof CategorySchema>;
export default mongoose.model<ICategory>("Category", CategorySchema);
