// Code Generated by Sidekick is for learning and experimentation purposes only.
import mongoose, { type InferSchemaType } from "mongoose";
import { COMMENT_VISIBILITY } from "../utils/constants";

const CommentSchema = new mongoose.Schema(
  {
    ticketId: { type: mongoose.Schema.Types.ObjectId, ref: "Ticket", required: true, index: true },
    authorId: { type: mongoose.Schema.Types.ObjectId, ref: "User", required: true },
    visibility: { type: String, enum: Object.values(COMMENT_VISIBILITY), default: COMMENT_VISIBILITY.PUBLIC, required: true },
    body: { type: String, trim: true, required: true, maxlength: 2000 },
    editedAt: { type: Date }
  },
  { timestamps: true, toJSON: { virtuals: true }, toObject: { virtuals: true } }
);

CommentSchema.virtual("attachments", {
  ref: "Attachment",
  localField: "_id",
  foreignField: "commentId"
});

CommentSchema.index({ ticketId: 1, createdAt: 1 });

export type IComment = InferSchemaType<typeof CommentSchema>;
export default mongoose.model<IComment>("Comment", CommentSchema);
