// Code Generated by Sidekick is for learning and experimentation purposes only.
import mongoose, { type InferSchemaType } from "mongoose";

const CounterSchema = new mongoose.Schema(
  {
    _id: { type: String, required: true },
    seq: { type: Number, default: 0 }
  },
  { versionKey: false }
);

export type ICounter = InferSchemaType<typeof CounterSchema>;
export default mongoose.model<ICounter>("Counter", CounterSchema);
