// Code Generated by Sidekick is for learning and experimentation purposes only.
import mongoose, { type InferSchemaType } from "mongoose";

const TicketAgentDecisionSchema = new mongoose.Schema(
  {
    ticketId: { type: mongoose.Schema.Types.ObjectId, ref: "Ticket", required: true },
    agentId: { type: mongoose.Schema.Types.ObjectId, ref: "User", required: true },
    decision: { type: String, enum: ["Rejected"], required: true },
    reason: { type: String, trim: true, maxlength: 500 },
    decidedAt: { type: Date, default: Date.now }
  },
  { versionKey: false }
);

TicketAgentDecisionSchema.index({ ticketId: 1, agentId: 1 }, { unique: true });
TicketAgentDecisionSchema.index({ agentId: 1, decidedAt: -1 });

export type ITicketAgentDecision = InferSchemaType<typeof TicketAgentDecisionSchema>;
export default mongoose.model<ITicketAgentDecision>("TicketAgentDecision", TicketAgentDecisionSchema);
