// Code Generated by Sidekick is for learning and experimentation purposes only.
import mongoose, { type InferSchemaType } from "mongoose";
import { USER_ROLES } from "../utils/constants";

const UserSchema = new mongoose.Schema(
  {
    firstName: { type: String, trim: true, required: true, maxlength: 50 },
    lastName: { type: String, trim: true, required: true, maxlength: 50 },
    email: { type: String, trim: true, required: true, lowercase: true, unique: true, maxlength: 254 },
    passwordHash: { type: String, required: true },
    role: { type: String, enum: Object.values(USER_ROLES), default: USER_ROLES.REQUESTER, required: true },
    isActive: { type: Boolean, default: true },
    lastLoginAt: { type: Date }
  },
  { timestamps: true }
);

export type IUser = InferSchemaType<typeof UserSchema>;
export default mongoose.model<IUser>("User", UserSchema);
