// Code Generated by Sidekick is for learning and experimentation purposes only.
import AttachmentModel from "../models/Attachment";
import type mongoose from "mongoose";

export async function createMany(
  params: {
    files?: Express.Multer.File[];
    ticketId: any;
    commentId?: any | null;
    uploadedBy: any;
  },
  session?: mongoose.ClientSession
) {
  const { files, ticketId, commentId = null, uploadedBy } = params;
  if (!files || files.length === 0) return [];

  const docs = files.map((f) => ({
    ticketId,
    commentId,
    uploadedBy,
    originalFilename: f.originalname,
    mimeType: f.mimetype,
    sizeBytes: f.size,
    storageKey: f.filename || f.originalname, // Fallback if no filename in memory storage
    data: f.buffer
  }));

  return AttachmentModel.insertMany(docs, { session });
}
