// Code Generated by Sidekick is for learning and experimentation purposes only.
import ApiError from "../utils/apiError";
import CategoryModel from "../models/Category";

export async function listActive() {
  return CategoryModel.find({ isActive: true }).sort({ sortOrder: 1, name: 1 });
}

export async function listAll() {
  return CategoryModel.find({}).sort({ isActive: -1, sortOrder: 1, name: 1 });
}

export async function createCategory(payload: { name: string; sortOrder?: number; isActive?: boolean }) {
  const doc = await CategoryModel.create({
    name: payload.name,
    // sortOrder: payload.sortOrder ?? 0,
    isActive: payload.isActive ?? true
  });
  return doc;
}

export async function updateCategory(id: string, payload: Partial<{ name: string; sortOrder: number; isActive: boolean }>) {
  const doc = await CategoryModel.findByIdAndUpdate(id, payload, {
    new: true,
    runValidators: true
  });
  if (!doc) throw new ApiError(404, "Category not found", "NOT_FOUND");
  return doc;
}

export async function deactivateCategory(id: string) {
  const doc = await CategoryModel.findByIdAndUpdate(
    id,
    { isActive: false },
    { new: true, runValidators: true }
  );
  if (!doc) throw new ApiError(404, "Category not found", "NOT_FOUND");
  return doc;
}
