// Code Generated by Sidekick is for learning and experimentation purposes only.
import express from "express";
import cors from "cors";
import helmet from "helmet";
import morgan from "morgan";

import env from "./config/env";
import { connectDB } from "./config/db";

import routes from "./routes/index.routes";
import notFound from "./middlewares/notFound";
import errorHandler from "./middlewares/errorHandler";

async function bootstrap() {
  await connectDB(env.MONGO_URI);

  const app = express();

  app.use(helmet());
  app.use(cors());
  app.use(express.json({ limit: "1mb" }));
  app.use(express.urlencoded({ extended: true }));
  if (env.NODE_ENV !== "test") app.use(morgan("dev"));

 app.get("/health", (_req, res) => {
  res.status(200).json({ success: true, status: "ok" });
});


  app.use("/api/v1", routes);

  app.use(notFound);
  app.use(errorHandler);

  app.listen(env.PORT, () => {
    // eslint-disable-next-line no-console
    console.log(`Server running on port ${env.PORT} (${env.NODE_ENV})`);
  });
}

bootstrap().catch((err) => {
  // eslint-disable-next-line no-console
  console.error("Failed to start server:", err);
  process.exit(1);
});
