// Code Generated by Sidekick is for learning and experimentation purposes only.
import asyncHandler from "../utils/asyncHandler";
import * as authService from "../services/auth.service";

import { Response, NextFunction, Request } from 'express';

export const register = asyncHandler(async (req, res) => {
  const { user, token } = await authService.register(req.body);
  res.status(201).json({ success: true, data: { user, token } });
});

export const login = asyncHandler(async (req, res) => {
  const { user, token } = await authService.login(req.body);
  res.status(200).json({ success: true, data: { user, token } });
});

export const me = asyncHandler(async (req: Request, res: Response) => {
  res.status(200).json({ success: true, data: req.user });
});
