// Code Generated by Sidekick is for learning and experimentation purposes only.
import asyncHandler from "../utils/asyncHandler";
import * as categoryService from "../services/category.service";

export const listCategories = asyncHandler(async (_req, res) => {
  const categories = await categoryService.listActive();
  res.status(200).json({ success: true, results: categories.length, data: categories });
});

// Agent-only (admin-like) endpoints
export const listAllCategories = asyncHandler(async (_req, res) => {
  const categories = await categoryService.listAll();
  res.status(200).json({ success: true, results: categories.length, data: categories });
});

export const createCategory = asyncHandler(async (req, res) => {
  const category = await categoryService.createCategory(req.body);
  res.status(201).json({ success: true, message: "Category created", data: category });
});

export const updateCategory = asyncHandler(async (req, res) => {
  const category = await categoryService.updateCategory(req.params.id, req.body);
  res.status(200).json({ success: true, message: "Category updated", data: category });
});

export const deleteCategory = asyncHandler(async (req, res) => {
  const category = await categoryService.deactivateCategory(req.params.id);
  res.status(200).json({ success: true, message: "Category deactivated", data: category });
});
