// Code Generated by Sidekick is for learning and experimentation purposes only.
import asyncHandler from "../utils/asyncHandler";
import * as commentService from "../services/comment.service";

export const addComment = asyncHandler(async (req, res) => {
  const comment = await commentService.addComment({
    user: req.user,
    ticketId: req.params.ticketId,
    body: req.body,
    files: req.files as Express.Multer.File[] | undefined
  });

  res.status(201).json({ success: true, message: "Comment added", data: comment });
});

export const listComments = asyncHandler(async (req, res) => {
  const comments = await commentService.listComments({ user: req.user, ticketId: req.params.ticketId });
  res.status(200).json({ success: true, results: comments.length, data: comments });
});
