// Code Generated by Sidekick is for learning and experimentation purposes only.
import express from "express";
import auth from "../middlewares/auth";
import requireRole from "../middlewares/requireRole";
import validate from "../middlewares/validate";
import { listQuerySchema } from "../validators/query.validator";
import { unassignSchema, completeSchema, rejectSchema } from "../validators/ticket.validator";
import * as ticketController from "../controllers/ticket.controller";

const router = express.Router();

router.use(auth, requireRole("Agent"));

router.get("/tickets", validate(listQuerySchema, "query"), ticketController.getAgentAssignedTickets);
router.get("/tickets/unassigned", validate(listQuerySchema, "query"), ticketController.getAgentUnassignedTickets);

router.post("/tickets/:id/claim", ticketController.claim);
router.post("/tickets/:id/start", ticketController.start);
router.post("/tickets/:id/unassign", validate(unassignSchema), ticketController.unassign);
router.post("/tickets/:id/complete", validate(completeSchema), ticketController.complete);
router.post("/tickets/:id/reject", validate(rejectSchema), ticketController.reject);

export default router;
