// Code Generated by Sidekick is for learning and experimentation purposes only.
import express from "express";
import validate from "../middlewares/validate";
import auth from "../middlewares/auth";
import { registerSchema, loginSchema } from "../validators/auth.validator";
import * as authController from "../controllers/auth.controller";

const router = express.Router();

router.post("/register", validate(registerSchema), authController.register);
router.post("/login", validate(loginSchema), authController.login);
router.get("/me", auth, authController.me);

export default router;
