// Code Generated by Sidekick is for learning and experimentation purposes only.
import express from "express";
import auth from "../middlewares/auth";
import requireRole from "../middlewares/requireRole";
import validate from "../middlewares/validate";
import * as categoryController from "../controllers/category.controller";
import { createCategorySchema, updateCategorySchema } from "../validators/category.validator";

const router = express.Router();

// Public (used by requester/agent ticket create dropdown)
router.get("/", categoryController.listCategories);

// Agent-only management
router.get("/all", auth, requireRole("Agent"), categoryController.listAllCategories);
router.post("/", auth, requireRole("Agent"), validate(createCategorySchema), categoryController.createCategory);
router.patch("/:id", auth, requireRole("Agent"), validate(updateCategorySchema), categoryController.updateCategory);
router.delete("/:id", auth, requireRole("Agent"), categoryController.deleteCategory);

export default router;
