// Code Generated by Sidekick is for learning and experimentation purposes only.
import express from "express";
import auth from "../middlewares/auth";
import validate from "../middlewares/validate";
import { uploadCommentFiles } from "../middlewares/upload";
import { addCommentSchema } from "../validators/comment.validator";
import * as commentController from "../controllers/comment.controller";

const router = express.Router();

router.get("/tickets/:ticketId/comments", auth, commentController.listComments);

router.post(
  "/tickets/:ticketId/comments",
  auth,
  uploadCommentFiles,
  validate(addCommentSchema),
  commentController.addComment
);

export default router;
