// Code Generated by Sidekick is for learning and experimentation purposes only.
import express from "express";
import authRoutes from "./auth.routes";
import ticketRoutes from "./tickets.routes";
import agentRoutes from "./agent.routes";
import categoryRoutes from "./categories.routes";
import commentRoutes from "./comments.routes";

const router = express.Router();

router.use("/auth", authRoutes);
router.use("/tickets", ticketRoutes);
router.use("/agent", agentRoutes);
router.use("/categories", categoryRoutes);
router.use("/", commentRoutes);

export default router;
