// Code Generated by Sidekick is for learning and experimentation purposes only.
import express from "express";
import auth from "../middlewares/auth";
import validate from "../middlewares/validate";
import { uploadTicketFiles } from "../middlewares/upload";
import { createTicketSchema } from "../validators/ticket.validator";
import { listQuerySchema } from "../validators/query.validator";
import * as ticketController from "../controllers/ticket.controller";

const router = express.Router();

// Code Generated by Sidekick is for learning and experimentation purposes only.
router.post(
  "/",
  auth,
  uploadTicketFiles,
  (req, _res, next) => {
    console.log("after multer body:", req.body);
    next();
  },
  ticketController.createTicket
);

router.get("/stats", auth, ticketController.getTicketStats);
router.get("/my", auth, validate(listQuerySchema, "query"), ticketController.getMyTickets);
router.get("/assigned", auth, validate(listQuerySchema, "query"), ticketController.getAgentAssignedTickets);
router.get("/unassigned", auth, validate(listQuerySchema, "query"), ticketController.getAgentUnassignedTickets);

// Agent Actions
router.get("/all/tickets", auth, ticketController.getAllTickets); // Use /all/tickets to avoid conflict with /:id

router.get("/:id", auth, ticketController.getTicketDetail);
router.get("/:id/history", auth, ticketController.history);
router.patch("/:id/claim", auth, ticketController.claim);
router.patch("/:id/start", auth, ticketController.start);
router.patch("/:id/unassign", auth, ticketController.unassign);
router.patch("/:id/complete", auth, ticketController.complete);
router.patch("/:id/reopen", auth, ticketController.reopen);
router.patch("/:id/reject", auth, ticketController.reject);

export default router;
