// Code Generated by Sidekick is for learning and experimentation purposes only.
import type { Query } from "mongoose";

type Options = { defaultSort?: string };

export default class APIFilters<T> {
  query: Query<T[], any>;
  queryStr: Record<string, any>;
  options: Required<Options>;
  private _page = 1;
  private _limit = 10;

  constructor(query: Query<T[], any>, queryStr: Record<string, any>, options: Options = {}) {
    this.query = query;
    this.queryStr = queryStr;
    this.options = { defaultSort: options.defaultSort || "-updatedAt" };
  }

  filter() {
    const queryCopy = { ...this.queryStr };
    const removeFields = ["sort", "fields", "q", "limit", "page"];
    removeFields.forEach((el) => delete queryCopy[el]);

    let qs = JSON.stringify(queryCopy);
    qs = qs.replace(/\b(gt|gte|lt|lte|in)\b/g, (match) => `$${match}`);

    this.query = this.query.find(JSON.parse(qs));
    return this;
  }

  sort() {
    if (this.queryStr.sort) {
      const sortBy = String(this.queryStr.sort).split(",").join(" ");
      this.query = this.query.sort(sortBy);
    } else {
      this.query = this.query.sort(this.options.defaultSort);
    }
    return this;
  }

  limitFields() {
  if (this.queryStr.fields) {
    const fields = String(this.queryStr.fields).split(",").join(" ");
    // Cast to any to bypass the complex Document intersection mismatch
    this.query = this.query.select(fields) as any;
  } else {
    this.query = this.query.select("-__v") as any;
  }
  return this;
}

  searchByQuery(textFieldsEnabled = true) {
    if (this.queryStr.q && textFieldsEnabled) {
      const qu = String(this.queryStr.q).split("-").join(" ").trim();
      if (qu) this.query = this.query.find({ $text: { $search: `"${qu}"` } } as any);
    }
    return this;
  }

  pagination() {
    const page = parseInt(String(this.queryStr.page || ""), 10) || 1;
    const limit = parseInt(String(this.queryStr.limit || ""), 10) || 10;
    const skipResults = (page - 1) * limit;

    this._page = page;
    this._limit = limit;

    this.query = this.query.skip(skipResults).limit(limit);
    return this;
  }

  getMeta(total: number) {
    const pages = Math.max(1, Math.ceil(total / this._limit));
    return { page: this._page, limit: this._limit, pages, total };
  }
}
