// Code Generated by Sidekick is for learning and experimentation purposes only.
import type { Request, Response, NextFunction, RequestHandler } from "express";

type AsyncFn = (req: Request, res: Response, next: NextFunction) => Promise<any> | any;

export default function asyncHandler(fn: AsyncFn): RequestHandler {
  return (req, res, next) => {
    Promise.resolve(fn(req, res, next)).catch(next); // IMPORTANT: catch(next), not catch(next())
  };
}
