// Code Generated by Sidekick is for learning and experimentation purposes only.
export const USER_ROLES = Object.freeze({
  REQUESTER: "Requester",
  AGENT: "Agent"
} as const);

export const TICKET_STATUS = Object.freeze({
  CREATED: "Created",
  ASSIGNED: "Assigned",
  STARTED: "Started",
  COMPLETED: "Completed"
} as const);

export const TICKET_TYPE = Object.freeze({
  INCIDENT: "Incident",
  SERVICE_REQUEST: "Service Request"
} as const);

export const TICKET_PRIORITY = Object.freeze({
  LOW: "Low",
  MEDIUM: "Medium",
  HIGH: "High",
  CRITICAL: "Critical"
} as const);

export const DEVICE_TYPE = Object.freeze({
  LAPTOP: "Laptop",
  DESKTOP: "Desktop",
  TABLET: "Tablet",
  MOBILE: "Mobile"
} as const);

export const OS_TYPE = Object.freeze({
  WINDOWS: "Windows",
  MACOS: "MacOS",
  MOBILE: "Mobile",
  OTHERS: "Others"
} as const);

export const LOCATION_TYPE = Object.freeze({
  OFFICE: "Office",
  REMOTE: "Remote"
} as const);

export const COMMENT_VISIBILITY = Object.freeze({
  PUBLIC: "Public",
  INTERNAL: "Internal"
} as const);

export const AUDIT_VISIBILITY = Object.freeze({
  PUBLIC: "Public",
  INTERNAL: "Internal"
} as const);

export const AUDIT_EVENT_TYPE = Object.freeze({
  TICKET_CREATED: "TicketCreated",
  ASSIGNED: "Assigned",
  STARTED: "Started",
  UNASSIGNED: "Unassigned",
  COMPLETED: "Completed",
  COMMENT_ADDED: "CommentAdded",
  ATTACHMENT_ADDED: "AttachmentAdded",
  REOPENED: "Reopened",
  REJECTED_BY_AGENT: "RejectedByAgent"
} as const);

export type UserRole = (typeof USER_ROLES)[keyof typeof USER_ROLES];
export type TicketStatus = (typeof TICKET_STATUS)[keyof typeof TICKET_STATUS];
export type TicketType = (typeof TICKET_TYPE)[keyof typeof TICKET_TYPE];
export type TicketPriority = (typeof TICKET_PRIORITY)[keyof typeof TICKET_PRIORITY];
export type DeviceType = (typeof DEVICE_TYPE)[keyof typeof DEVICE_TYPE];
export type OSType = (typeof OS_TYPE)[keyof typeof OS_TYPE];
export type LocationType = (typeof LOCATION_TYPE)[keyof typeof LOCATION_TYPE];
export type CommentVisibility = (typeof COMMENT_VISIBILITY)[keyof typeof COMMENT_VISIBILITY];
export type AuditVisibility = (typeof AUDIT_VISIBILITY)[keyof typeof AUDIT_VISIBILITY];
export type AuditEventType = (typeof AUDIT_EVENT_TYPE)[keyof typeof AUDIT_EVENT_TYPE];
