// Code Generated by Sidekick is for learning and experimentation purposes only.
import mongoose from "mongoose";

export function isValidObjectId(id: string) {
  return mongoose.Types.ObjectId.isValid(id);
}
