// Code Generated by Sidekick is for learning and experimentation purposes only.
import type { Response, NextFunction } from "express";
import jwt from "jsonwebtoken";
import env from "../config/env";
import ApiError from "../utils/apiError";
import UserModel from "../models/User";

export default async function auth(req: any, _res: Response, next: NextFunction) {
  try {
    const header = req.headers.authorization || "";
    const [type, token] = header.split(" ");

    if (type !== "Bearer" || !token) {
      return next(new ApiError(401, "Authentication required", "UNAUTHORIZED"));
    }

    const payload = jwt.verify(token, env.JWT_SECRET) as { sub: string };
    const user = await UserModel.findById(payload.sub).select("-passwordHash");

    if (!user || !user.isActive) {
      return next(new ApiError(401, "Invalid user", "UNAUTHORIZED"));
    }

    req.user = user.toObject();
    next();
  } catch {
    return next(new ApiError(401, "Invalid or expired token", "UNAUTHORIZED"));
  }
}
 