// Code Generated by Sidekick is for learning and experimentation purposes only.
import type { Request, Response, NextFunction } from "express";
import ApiError from "../utils/apiError";

export default function errorHandler(err: any, _req: Request, res: Response, _next: NextFunction) {
  let statusCode = err.statusCode || 500;
  let code = err.code || "INTERNAL_ERROR";
  let message = err.message || "Something went wrong";
  let details = err.details;
 console.error(err?.stack || err); 
  if (err.name === "CastError") {
    statusCode = 400;
    code = "INVALID_ID";
    message = `Invalid ${err.path}: ${err.value}`;
  }

  if (err.name === "ValidationError") {
    statusCode = 400;
    code = "DB_VALIDATION_ERROR";
    message = "Database validation error";
    details = Object.values(err.errors || {}).map((e: any) => ({ path: e.path, message: e.message }));
  }

  if (err.code === 11000) {
    statusCode = 409;
    code = "DUPLICATE_KEY";
    const fields = Object.keys(err.keyValue || {});
    message = `Duplicate value for: ${fields.join(", ")}`;
    details = err.keyValue;
  }

  if (err.name === "JsonWebTokenError") {
    statusCode = 401;
    code = "INVALID_TOKEN";
    message = "Invalid token";
  }
  if (err.name === "TokenExpiredError") {
    statusCode = 401;
    code = "TOKEN_EXPIRED";
    message = "Token expired";
  }

  if (err.name === "MulterError") {
    statusCode = 400;
    code = "UPLOAD_ERROR";
    message = err.message;
  }

  if (!(err instanceof ApiError) && statusCode === 500) {
    code = "INTERNAL_ERROR";
  }

  res.status(statusCode).json({ success: false, code, message, details });
}
