// Code Generated by Sidekick is for learning and experimentation purposes only.
import type { Request, Response, NextFunction } from "express";

export default function notFound(req: Request, res: Response, _next: NextFunction) {
  res.status(404).json({
    success: false,
    code: "NOT_FOUND",
    message: `Route not found: ${req.method} ${req.originalUrl}`
  });
}
