// Code Generated by Sidekick is for learning and experimentation purposes only.
import type { Request, Response, NextFunction } from "express";
import ApiError from "../utils/apiError";
import type { UserRole } from "../utils/constants";

export default function requireRole(role: UserRole) {
  return (req: Request, _res: Response, next: NextFunction) => {
    if (!req.user) return next(new ApiError(401, "Authentication required", "UNAUTHORIZED"));
    if (req.user.role !== role) return next(new ApiError(403, "Forbidden", "FORBIDDEN"));
    next();
  };
}
