// Code Generated by Sidekick is for learning and experimentation purposes only.
import multer from "multer";
import path from "path";
import fs from "fs";
import env from "../config/env";
import ApiError from "../utils/apiError";

function ensureDir(dir: string) {
  if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });
}
ensureDir(env.UPLOAD_DIR);

const storage = multer.memoryStorage();

const allowed = new Set(["image/png", "image/jpeg", "application/pdf"]);

function fileFilter(_req: any, file: Express.Multer.File, cb: multer.FileFilterCallback) {
  if (!allowed.has(file.mimetype)) return cb(new ApiError(415, "Only PNG, JPG, PDF allowed", "UNSUPPORTED_MEDIA_TYPE"));
  cb(null, true);
}

const upload = multer({
  storage,
  fileFilter,
  limits: { fileSize: 10 * 1024 * 1024 }
});

export const uploadTicketFiles = upload.array("attachments", 5);
export const uploadCommentFiles = upload.array("attachments", 5);
