// Code Generated by Sidekick is for learning and experimentation purposes only.
import type { Request, Response, NextFunction } from "express";
import type Joi from "joi";
import ApiError from "../utils/apiError";

export default function validate(schema: Joi.ObjectSchema, property: "body" | "query" | "params" = "body") {
  return (req: Request, _res: Response, next: NextFunction) => {
    const { error, value } = schema.validate((req as any)[property], {
      abortEarly: false,
      stripUnknown: true
    });

    if (error) {
      return next(new ApiError(400, "Validation failed", "VALIDATION_ERROR", error.details));
    }

    (req as any)[property] = value;
    next();
  };
}
