// Code Generated by Sidekick is for learning and experimentation purposes only.
import Joi from "joi";

export const createCategorySchema = Joi.object({
  name: Joi.string().trim().min(2).max(80).required(),
//   sortOrder: Joi.number().integer().min(0).max(9999).default(0),
  isActive: Joi.boolean().default(true)
});

export const updateCategorySchema = Joi.object({
  name: Joi.string().trim().min(2).max(80),
//   sortOrder: Joi.number().integer().min(0).max(9999),
  isActive: Joi.boolean()
}).min(1);
