// Code Generated by Sidekick is for learning and experimentation purposes only.
import Joi from "joi";
import { COMMENT_VISIBILITY } from "../utils/constants";

export const addCommentSchema = Joi.object({
  body: Joi.string().trim().min(1).max(2000).required(),
  visibility: Joi.string().valid(...Object.values(COMMENT_VISIBILITY)).default(COMMENT_VISIBILITY.PUBLIC)
});
