// Code Generated by Sidekick is for learning and experimentation purposes only.
import Joi from "joi";

export const listQuerySchema = Joi.object({
  sort: Joi.string(),
  fields: Joi.string(),
  q: Joi.string().allow(""),
  limit: Joi.number().integer().min(1).max(100).default(10),
  page: Joi.number().integer().min(1).default(1),

  status: Joi.string(),
  type: Joi.string(),
  priority: Joi.string(),
  categoryId: Joi.string(),
  operatingSystem: Joi.string(),
  deviceType: Joi.string(),
  location: Joi.string()
}).unknown(true);
