// Code Generated by Sidekick is for learning and experimentation purposes only.
import Joi from "joi";
import { DEVICE_TYPE, LOCATION_TYPE, OS_TYPE, TICKET_PRIORITY, TICKET_TYPE } from "../utils/constants";

export const createTicketSchema = Joi.object({
  title: Joi.string().trim().max(50).required(),
  description: Joi.string().trim().max(300).required(),
  type: Joi.string().valid(...Object.values(TICKET_TYPE)).required(),
  categoryId: Joi.string().optional(),
  categoryName: Joi.string().optional(),
  priority: Joi.string().valid(...Object.values(TICKET_PRIORITY)).required(),
  deviceType: Joi.string().valid(...Object.values(DEVICE_TYPE)).required(),
  operatingSystem: Joi.string().valid(...Object.values(OS_TYPE)).required(),
  location: Joi.string().valid(...Object.values(LOCATION_TYPE)).required()
});

export const unassignSchema = Joi.object({
  reason: Joi.string().trim().min(5).max(500).required()
});

export const completeSchema = Joi.object({
  resolutionSummary: Joi.string().trim().min(5).max(1000).required()
});

export const rejectSchema = Joi.object({
  reason: Joi.string().trim().max(500).optional()
});
