// Code Generated by Sidekick is for learning and experimentation purposes only.
import dotenv from "dotenv";
import Joi from "joi";

dotenv.config();

const schema = Joi.object({
  NODE_ENV: Joi.string().valid("development", "test", "production").default("development"),
  PORT: Joi.number().integer().min(1).max(65535).default(4000),
  MONGO_URI: Joi.string().required(),
  JWT_SECRET: Joi.string().min(16).required(),
  JWT_EXPIRES_IN: Joi.string().default("7d"),
  UPLOAD_DIR: Joi.string().default("uploads")
}).unknown(true);

const { value, error } = schema.validate(process.env);
if (error) throw new Error(`Environment validation error: ${error.message}`);

const env = value as {
  NODE_ENV: "development" | "test" | "production";
  PORT: number;
  MONGO_URI: string;
  JWT_SECRET: string;
  JWT_EXPIRES_IN: string;
  UPLOAD_DIR: string;
};

export default env;
